version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:2
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  idp:
    container_name: idp
    image: quay.io/keycloak/keycloak:latest

  pgadmin:
    container_name: pgadmin
    image: docker.io/dpage/pgadmin4:latest

volumes:
  postgres-data: